---
title: "Disclaimer"
output: html_document
---

## Authorship

This web-based service has been develop by the [Vegetation Modeling Group](http://vegmod.ctfc.cat/)
at [Forest Science and Technology Centre of Catalonia (CTFC)](http://www.ctfc.cat),
in collaboration with the
[Center for Ecological Research and Forestry Applications (CREAF)](http://www.creaf.cat/):

  + *Idea and conceptual design*: Miquel de Cáceres (CTFC/CREAF), Víctor Granda (CTFC), Antoine Cabon (CTFC/CREAF) & Jordi Martínez Vilalta (UAB/CREAF)
  
  + *Package development*: Miquel De Cáceres (CTFC/CREAF), Antoine Cabon (CTFC/CREAF) & Víctor Granda (CTFC).
  
  + *User interface*: Víctor Granda (CTFC).
  
  + *Contact*: Miquel De Cáceres (miquelcaceres@gmail.com)

---

## Scientific advisory board

+ Jordi Martínez Vilalta (UAB/CREAF)
+ Maurizio Mencuccini (ICREA)
+ Nicolas Martin-StPaul (INRA)
+ Lluís Coll (CTFC/CREAF)
+ Juli G. Pausas (CIDE-CSIC)
+ Pere Casals (CTFC)
+ Lluís Brotons (CTFC/CREAF/CSIC)
+ Pilar Llorens (IDAEA-CSIC)
+ Rafael Poyatos (CREAF)
+ Albert Álvarez (CREAF)
+ Jordi Vayreda (CREAF)
+ Mario Beltrán (AGS-CTFC)

---

## Funding projects

  + *Projects*: **FORESTCAST** (CGL2014-59742-C2-2-R,
    Ministerio de Economía y Competitividad), **DRESS** (CGL2017-89149-C2-2-R, Ministerio de Economía y Competitividad).

  + *Fellowships*: RYC-2012-11109 to M. De Cáceres (Ministerio de Economía y
    Ciencia).

---

## Disclaimer

The data offered in this website is the result of modelling exercises and the
accuracy of results may be impaired by several factors, like inaccuracies of
input data, inappropriate model design or parameterization. Users should be aware
of all these limitations when using the data offered here. We decline all
responsibility for how the data in this website is used by third parties.
